if (typeof global !== "undefined") {
    // we could be in node
    // this only exports a connected api
    module.exports = {
        xtract_is_denormal: xtract_is_denormal,
        xtract_assert_array: xtract_assert_array,
        xtract_assert_positive_integer: xtract_assert_positive_integer,
        xtract_array_sum: xtract_array_sum,
        xtract_array_copy: xtract_array_copy,
        xtract_array_min: xtract_array_min,
        xtract_array_max: xtract_array_max,
        xtract_array_scale: xtract_array_scale,
        xtract_array_normalise: xtract_array_normalise,
        xtract_array_bound: xtract_array_bound,
        xtract_array_interlace: xtract_array_interlace,
        xtract_array_deinterlace: xtract_array_deinterlace,
        xtract_get_number_of_frames: xtract_get_number_of_frames,
        xtract_get_data_frames: xtract_get_data_frames,
        xtract_process_frame_data: xtract_process_frame_data,
        xtract_array_to_JSON: xtract_array_to_JSON,
        xtract_frame_from_array: xtract_frame_from_array,
        xtract_mean: xtract_mean,
        xtract_temporal_centroid: xtract_temporal_centroid,
        xtract_variance: xtract_variance,
        xtract_standard_deviation: xtract_standard_deviation,
        xtract_average_deviation: xtract_average_deviation,
        xtract_skewness_kurtosis: xtract_skewness_kurtosis,
        xtract_skewness: xtract_skewness,
        xtract_kurtosis: xtract_kurtosis,
        xtract_spectral_centroid: xtract_spectral_centroid,
        xtract_spectral_mean: xtract_spectral_mean,
        xtract_spectral_variance: xtract_spectral_variance,
        xtract_spectral_spread: xtract_spectral_spread,
        xtract_spectral_standard_deviation: xtract_spectral_standard_deviation,
        xtract_spectral_skewness: xtract_spectral_skewness,
        xtract_spectral_kurtosis: xtract_spectral_kurtosis,
        xtract_irregularity_k: xtract_irregularity_k,
        xtract_irregularity_j: xtract_irregularity_j,
        xtract_tristimulus: xtract_tristimulus,
        xtract_tristimulus_1: xtract_tristimulus_1,
        xtract_tristimulus_2: xtract_tristimulus_2,
        xtract_tristimulus_3: xtract_tristimulus_3,
        xtract_smoothness: xtract_smoothness,
        xtract_zcr: xtract_zcr,
        xtract_rolloff: xtract_rolloff,
        xtract_loudness: xtract_loudness,
        xtract_flatness: xtract_flatness,
        xtract_flatness_db: xtract_flatness_db,
        xtract_tonality: xtract_tonality,
        xtract_crest: xtract_crest,
        xtract_noisiness: xtract_noisiness,
        xtract_rms_amplitude: xtract_rms_amplitude,
        xtract_spectral_inharmonicity: xtract_spectral_inharmonicity,
        xtract_power: xtract_power,
        xtract_odd_even_ratio: xtract_odd_even_ratio,
        xtract_sharpness: xtract_sharpness,
        xtract_spectral_slope: xtract_spectral_slope,
        xtract_lowhigh: xtract_lowhigh,
        xtract_lowest_value: xtract_lowest_value,
        xtract_highest_value: xtract_highest_value,
        xtract_sum: xtract_sum,
        xtract_nonzero_count: xtract_nonzero_count,
        xtract_hps: xtract_hps,
        xtract_f0: xtract_f0,
        xtract_failsafe_f0: xtract_failsafe_f0,
        xtract_wavelet_f0: xtract_wavelet_f0,
        xtract_midicent: xtract_midicent,
        xtract_spectral_fundamental: xtract_spectral_fundamental,
        xtract_energy: xtract_energy,
        xtract_spectrum: xtract_spectrum,
        xtract_complex_spectrum: xtract_complex_spectrum,
        xtract_mfcc: xtract_mfcc,
        xtract_dct: xtract_dct,
        xtract_dct_2: xtract_dct_2,
        xtract_autocorrelation: xtract_autocorrelation,
        xtract_amdf: xtract_amdf,
        xtract_asdf: xtract_asdf,
        xtract_bark_coefficients: xtract_bark_coefficients,
        xtract_peak_spectrum: xtract_peak_spectrum,
        xtract_harmonic_spectrum: xtract_harmonic_spectrum,
        xtract_lpc: xtract_lpc,
        xtract_lpcc: xtract_lpcc,
        xtract_pcp: xtract_pcp,
        xtract_yin: xtract_yin,
        xtract_onset: xtract_onset,
        xtract_resample: xtract_resample,
        xtract_init_dft: xtract_init_dft,
        xtract_init_dct: xtract_init_dct,
        xtract_init_mfcc: xtract_init_mfcc,
        xtract_init_wavelet: xtract_init_wavelet,
        xtract_init_pcp: xtract_init_pcp,
        xtract_init_bark: xtract_init_bark,
        xtract_init_chroma: xtract_init_chroma,
        xtract_apply_window: xtract_apply_window,
        xtract_create_window: xtract_create_window,
        xtract_chroma: xtract_chroma,
        HarmonicSpectrumData:HarmonicSpectrumData,
        PeakSpectrumData: PeakSpectrumData,
        SpectrumData: SpectrumData,
        TimeData: TimeData,
        jsXtract: jsXtract
    };
} else if (typeof window !== "undefined" || typeof self !== "undefined") {
    // Browser!!
    Object.defineProperties(jsXtract,{
        xtract_is_denormal: {value: xtract_is_denormal},
        xtract_assert_array: {value: xtract_assert_array},
        xtract_assert_positive_integer: {value: xtract_assert_positive_integer},
        xtract_array_sum: {value: xtract_array_sum},
        xtract_array_copy: {value: xtract_array_copy},
        xtract_array_min: {value: xtract_array_min},
        xtract_array_max: {value: xtract_array_max},
        xtract_array_scale: {value: xtract_array_scale},
        xtract_array_normalise: {value: xtract_array_normalise},
        xtract_array_bound: {value: xtract_array_bound},
        xtract_array_interlace: {value: xtract_array_interlace},
        xtract_array_deinterlace: {value: xtract_array_deinterlace},
        xtract_get_number_of_frames: {value: xtract_get_number_of_frames},
        xtract_get_data_frames: {value: xtract_get_data_frames},
        xtract_process_frame_data: {value: xtract_process_frame_data},
        xtract_array_to_JSON: {value: xtract_array_to_JSON},
        xtract_frame_from_array: {value: xtract_frame_from_array},
        xtract_mean: {value: xtract_mean},
        xtract_temporal_centroid: {value: xtract_temporal_centroid},
        xtract_variance: {value: xtract_variance},
        xtract_standard_deviation: {value: xtract_standard_deviation},
        xtract_average_deviation: {value: xtract_average_deviation},
        xtract_skewness_kurtosis: {value: xtract_skewness_kurtosis},
        xtract_skewness: {value: xtract_skewness},
        xtract_kurtosis: {value: xtract_kurtosis},
        xtract_spectral_centroid: {value: xtract_spectral_centroid},
        xtract_spectral_mean: {value: xtract_spectral_mean},
        xtract_spectral_variance: {value: xtract_spectral_variance},
        xtract_spectral_spread: {value: xtract_spectral_spread},
        xtract_spectral_standard_deviation: {value: xtract_spectral_standard_deviation},
        xtract_spectral_skewness: {value: xtract_spectral_skewness},
        xtract_spectral_kurtosis: {value: xtract_spectral_kurtosis},
        xtract_irregularity_k: {value: xtract_irregularity_k},
        xtract_irregularity_j: {value: xtract_irregularity_j},
        xtract_tristimulus: {value: xtract_tristimulus},
        xtract_tristimulus_1: {value: xtract_tristimulus_1},
        xtract_tristimulus_2: {value: xtract_tristimulus_2},
        xtract_tristimulus_3: {value: xtract_tristimulus_3},
        xtract_smoothness: {value: xtract_smoothness},
        xtract_zcr: {value: xtract_zcr},
        xtract_rolloff: {value: xtract_rolloff},
        xtract_loudness: {value: xtract_loudness},
        xtract_flatness: {value: xtract_flatness},
        xtract_flatness_db: {value: xtract_flatness_db},
        xtract_tonality: {value: xtract_tonality},
        xtract_crest: {value: xtract_crest},
        xtract_noisiness: {value: xtract_noisiness},
        xtract_rms_amplitude: {value: xtract_rms_amplitude},
        xtract_spectral_inharmonicity: {value: xtract_spectral_inharmonicity},
        xtract_power: {value: xtract_power},
        xtract_odd_even_ratio: {value: xtract_odd_even_ratio},
        xtract_sharpness: {value: xtract_sharpness},
        xtract_spectral_slope: {value: xtract_spectral_slope},
        xtract_lowhigh: {value: xtract_lowhigh},
        xtract_lowest_value: {value: xtract_lowest_value},
        xtract_highest_value: {value: xtract_highest_value},
        xtract_sum: {value: xtract_sum},
        xtract_nonzero_count: {value: xtract_nonzero_count},
        xtract_hps: {value: xtract_hps},
        xtract_f0: {value: xtract_f0},
        xtract_failsafe_f0: {value: xtract_failsafe_f0},
        xtract_wavelet_f0: {value: xtract_wavelet_f0},
        xtract_midicent: {value: xtract_midicent},
        xtract_spectral_fundamental: {value: xtract_spectral_fundamental},
        xtract_energy: {value: xtract_energy},
        xtract_spectrum: {value: xtract_spectrum},
        xtract_complex_spectrum: {value: xtract_complex_spectrum},
        xtract_mfcc: {value: xtract_mfcc},
        xtract_dct: {value: xtract_dct},
        xtract_dct_2: {value: xtract_dct_2},
        xtract_autocorrelation: {value: xtract_autocorrelation},
        xtract_amdf: {value: xtract_amdf},
        xtract_asdf: {value: xtract_asdf},
        xtract_bark_coefficients: {value: xtract_bark_coefficients},
        xtract_peak_spectrum: {value: xtract_peak_spectrum},
        xtract_harmonic_spectrum: {value: xtract_harmonic_spectrum},
        xtract_lpc: {value: xtract_lpc},
        xtract_lpcc: {value: xtract_lpcc},
        xtract_pcp: {value: xtract_pcp},
        xtract_yin: {value: xtract_yin},
        xtract_onset: {value: xtract_onset},
        xtract_resample: {value: xtract_resample},
        xtract_init_dft: {value: xtract_init_dft},
        xtract_init_dct: {value: xtract_init_dct},
        xtract_init_mfcc: {value: xtract_init_mfcc},
        xtract_init_wavelet: {value: xtract_init_wavelet},
        xtract_init_pcp: {value: xtract_init_pcp},
        xtract_init_bark: {value: xtract_init_bark},
        xtract_init_chroma: {value: xtract_init_chroma},
        xtract_apply_window: {value: xtract_apply_window},
        xtract_create_window: {value: xtract_create_window},
        xtract_chroma: {value: xtract_chroma},
        HarmonicSpectrumData: {value: HarmonicSpectrumData},
        PeakSpectrumData: {value: PeakSpectrumData},
        SpectrumData: {value: SpectrumData},
        TimeData: {value: TimeData},
        jsXtract: {value: jsXtract}
    });
}
