engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: true
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: true
        max: 20
  fixme:
    enabled: true
ratings:
  paths:
  - "modules/*.js"
exclude_paths:
- "jsXtract.min.js"
- "modules/chroma/*.json"
